version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp1
    ports:
      - '2345:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_NAME: myapp1
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
