version: '3'
services:
  client_dev:
    build: ./client
    command: sh -c "npm run dev"
    container_name: pc-client-dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    working_dir: /home/app/client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/v1
      NEXT_PUBLIC_NETWORK_API_URL: http://api_dev:3001/v1
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '2345:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PORT: '${DB_PORT}'
    depends_on:
      - postgres
