version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '2345:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PORT: '${DB_PORT}'
    depends_on:
      - postgres
